routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AppController@index')->name('index');
Route::get('/about')->uses('HomeController@about')->name('about');
Route::get('/firesafety')->uses('HomeController@firesafety')->name('firesafety');
Route::get('/view-images/{id}')->uses('HomeController@viewImages')->name('view-images');

Auth::routes();

Route::prefix('/')->middleware(['auth', 'two_factor_auth'])->namespace('Dashboard')->group( function(){

    Route::resource('dashboard/photos', 'Photos\PhotosController');
    Route::resource('dashboard/category', 'Category\CategoryController');
    Route::resource('dashboard/profile-settings', 'UserSettings\UserSettingsController');

    //Change password
    Route::get('dashboard/change_password', 'UserSettings\UserSettingsController@change_password_form')->name('change_password');
    Route::post('dashboard/change_password', 'UserSettings\UserSettingsController@change_password')->name('change_password');

    //Restore Category
    Route::get('dashboard/category/restore/{category}', 'Category\CategoryController@restore')->name('restore');
    Route::post('dashboard/category/restore/{category}', 'Category\CategoryController@restore')->name('restore');

    //Restore Photos
    Route::get('dashboard/photos/restore/{photo}', 'Photos\PhotosController@restore');
    Route::post('dashboard/photos/restore/{photo}', 'Photos\PhotosController@restore');

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
});

Route::get('/2fa', 'TwoFactorController@show2faForm');
Route::post('/2fa', 'TwoFactorController@verifyToken');

resources/views/partials/nav/nav_header.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="#"><img src="{{ asset('/storage/logo.png') }}" class="logo"
            style="position: relative; width: 50px; left: -2px; background-size: contain;"> <span
            style="font-size: 17px;">Fire Inspection Pro</span>
    </a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>
    <li class="nav-item dropdown ml-auto">
        <a id="userDropdown" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @foreach($user as $data)
            @if($data->profile_pic == '')
            <img src="{{ asset('/storage/profile_pic/default_profile_pic.png') }}" class="img">
            @else
            <img src="{{ asset('/storage/profile_pic/'.$data->profile_pic.'') }}" class="img">
            @endif
            @endforeach
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
            <a class="dropdown-item small" href="{{ route('profile-settings.index') }}">Profile
                Settings</a>
            <a class="dropdown-item small" href="{{ route('change_password') }}">Change
                Password</a>
            <a class="dropdown-item small" href="{{ route('logout') }}" onclick="event.preventDefault();"
                id="logout">Logout
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </a>
        </div>
    </li>
</nav>

resources/views/partials/nav/nav_sidebar.blade.php
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav" style="margin-top: 21px;">
                    <a class="nav-link" href="/dashboard">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Dashboard
                    </a>
                    <a class="nav-link" href="{{ route('photos.index') }}">
                        <div class="sb-nav-link-icon"><i class="far fa-file-image"></i></div>
                        Photos
                    </a>
                    <a class="nav-link" href="{{ route('category.index') }}">
                        <div class="sb-nav-link-icon"><i class="fas fa-list-ul"></i></div>
                        Category
                    </a>
                    {{-- <a class="nav-link" href="{{ route('profile-settings.index') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-user-cog"></i></div>
                    Profile Settings
                    </a> --}}
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                        aria-expanded="false" aria-controls="collapseLayouts">
                        <div class="sb-nav-link-icon">
                            <i class="fas fa-user-cog"></i>
                        </div>
                        Profile Settings
                        <div class="sb-sidenav-collapse-arrow">
                            <i class="fas fa-angle-down"></i></div>
                    </a>
                    <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
                        data-parent="#sidenavAccordion">
                        <nav class="sb-sidenav-menu-nested nav">
                            <a class="nav-link" href="{{ route('profile-settings.index') }}">User Profile</a>
                            <a class="nav-link" href="{{ route('change_password') }}">Change
                                Password</a>
                        </nav>
                    </div>
                </div>
            </div>
        </nav>
    </div>

</div>