routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AppController@index')->name('index');
Route::get('/about')->uses('HomeController@about')->name('about');
Route::get('/firesafety')->uses('HomeController@firesafety')->name('firesafety');
Route::get('/view-images/{id}')->uses('HomeController@viewImages')->name('view-images');

Auth::routes();

Route::prefix('/')->middleware(['auth', 'two_factor_auth'])->namespace('Dashboard')->group( function(){

    Route::resource('dashboard/photos', 'Photos\PhotosController');
    Route::resource('dashboard/category', 'Category\CategoryController');
    Route::resource('dashboard/profile-settings', 'UserSettings\UserSettingsController');

    //Change password
    Route::get('dashboard/change_password', 'UserSettings\UserSettingsController@change_password_form')->name('change_password');
    Route::post('dashboard/change_password', 'UserSettings\UserSettingsController@change_password')->name('change_password');

    //Restore Category
    Route::get('dashboard/category/restore/{category}', 'Category\CategoryController@restore')->name('restore');
    Route::post('dashboard/category/restore/{category}', 'Category\CategoryController@restore')->name('restore');

    //Restore Photos
    Route::get('dashboard/photos/restore/{photo}', 'Photos\PhotosController@restore');
    Route::post('dashboard/photos/restore/{photo}', 'Photos\PhotosController@restore');

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
});

Route::get('/2fa', 'TwoFactorController@show2faForm');
Route::post('/2fa', 'TwoFactorController@verifyToken');

app/Models/Dashboard/Category.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Model;
use App\Models\Dashboard\Photo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function photos()
    {
        return $this->hasMany(Photo::class);
    }
}

app/Models/Dashboard/Photo.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Model;
use App\Models\Dashboard\Category;
use Illuminate\Database\Eloquent\SoftDeletes;

class Photo extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Dashboard/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Dashboard\Category;
use DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = Category::all();
        // Category::where('id', 3)->withTrashed()->get();
        if(request()->ajax())
        {
            return DataTables::of(Category::withTrashed()->latest()->get())
                ->addColumn('action', function($data){
                    if($data->deleted_at == null) {
                    $actionButtons = '<a href="/dashboard/category/'.$data->id.'/edit" class="mr-2 btn btn-warning editBtn">
                                        <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <form action="" style="display: inline">
                                            '.csrf_field().'
                                            <button type="button" class="mr-2 btn btn-danger deleteBtn" onclick="deleteData('.$data->id.')">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                        <button type="button" class="btn btn-primary" disabled style="opacity: .5;">
                                            <i class="fas fa-trash-restore"></i>
                                        </button>';
                    return $actionButtons;
                    } else{
                        $actionButtons = '<a class="mr-2 btn btn-warning editBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <button class="mr-2 btn btn-danger deleteBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                        <form action="/dashboard/category/restore/'.$data->id.'" method="POST" style="display: inline;>
                                        '.csrf_field().'
                                            <button type="button" class="btn btn-primary" onclick="restoreData('.$data->id.')">
                                                <i class="fas fa-trash-restore"></i>
                                            </button>
                                        </form>';

                        return $actionButtons;
                    }
                })
                ->rawColumns(['action'])
                ->make(true);
               
        };

        return view('dashboard.category.index', compact('data'));
    }

    public function getId($id)
    {
        $data = Category::find($id);

        return $data;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'category' => 'required',
        ]);

        $categories = new Category;

        $categories->category_name = $request->input('category');

        $categories->save();

        return redirect()->route('category.index')->with('success', 'Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('dashboard.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $category->category_name = $request->input('category');

        $category->save();

        return redirect()->route('category.index')->with('success', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);

        $category->delete();

        return redirect()->route('category.index')->with('delete-success', 'Deleted');
    }

    public function restore($id)
    {
        Category::withTrashed()->find($id)->restore();
        
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;;
use App\Models\Dashboard\Category;
use App\Models\Dashboard\Photo;

class HomeController extends Controller
{
    public function index(){

        $photos = Photo::count();
        $category = Category::count();
        
        return view('dashboard.index', compact(['photos', 'category']));
    }
    
}

app/Http/Controllers/Dashboard/Photos/PhotosController.php
<?php

namespace App\Http\Controllers\Dashboard\Photos;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Dashboard\Photo;
use App\Models\Dashboard\Category;
use DataTables;
use File;

class PhotosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
        {
            return DataTables::of(Photo::withTrashed()->latest()->get())
                ->editColumn('photo', function($data){

                $images = explode('|', $data->photo);
                $imgUrl = $data->photo ? 'photos/'.$images[0] : 'default_image.png';
                $photo = '
                    <a href="/storage/uploads/'.$imgUrl.'" class="image-popup" title="'.$data->title.'">
                        <div class="tbl-img">
                            <img src="/storage/uploads/'.$imgUrl.'" alt="'.$data->title.'">
                        </div>
                    </a>
                ';
                    return $photo;
                })

                ->editColumn('category_name', function($data){

                    $category = $data->category->category_name;

                    return $category;
                })

                ->editColumn('title',function($data){
                    return \Str::limit(strip_tags($data->title),10);

                 })

                ->editColumn('description',function($data){
                    return \Str::limit(strip_tags($data->description),30);

                 })

                ->addColumn('action', function($data){
                    if($data->deleted_at == null) {
                    $actionButtons = '<a href="/dashboard/photos/'.$data->id.'/edit" class="mr-2 btn btn-warning editBtn">
                                        <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <form action="" style="display: inline;">
                                            '.csrf_field().'
                                            <button type="button" class="btn btn-danger deleteBtn" onclick="deleteData('.$data->id.')">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                        <button type="button" class="btn btn-primary" disabled style="opacity: .5;">
                                            <i class="fas fa-trash-restore"></i>
                                        </button>';
                    return $actionButtons;
                    } else{
                        $actionButtons = '<a class="mr-2 btn btn-warning editBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <button class="mr-2 btn btn-danger deleteBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                        <form action="/dashboard/photos/restore/'.$data->id.'" method="POST" style="display: inline;>
                                        '.csrf_field().'
                                            <button type="button" class="btn btn-primary" onclick="restoreData('.$data->id.')">
                                                <i class="fas fa-trash-restore"></i>
                                            </button>
                                        </form>';
                    return $actionButtons;
                    }
                })
                ->rawColumns(['action', 'photo', 'category_name', 'title', 'description'])
                ->make(true);
        };

        return view('dashboard.photos.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('dashboard.photos.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'category' => 'required',
            // 'photo' => 'required|image|nullable|mimes:jpeg,png,jpg,gif,svg',

        ]);

        $input=$request->all();
            $images=array();
            $files = $request->input('website_image');
            if($files){
                foreach($files as $file) {
                    $filename = 'img_'.uniqid().'.png';
                    $dataImg  = explode(',', $file);
                    $decoded  = base64_decode($dataImg[1]);
                    file_put_contents(storage_path(). '/app/public/uploads/photos/'.$filename,$decoded);
                    $images[]=$filename;
                }
            }

        $data = new Photo;
        $data->title = $request->input('title');
        $data->description = $request->input('description');
        $data->category_id = $request->input('category');
        $data->photo = implode("|",$images);

        $data->save();

        return redirect()->route('photos.index')->with('success', 'Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $data = Photo::find($id);
        return view('dashboard.photos.edit', compact('data', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $data = Photo::find($id);
        $data->title = $request->input('title');
        $data->description = $request->input('description');
        $data->category_id = $request->category_id;

        $input=$request->all();
            $images=array();
            $files = $request->input('website_image');
            if($files){
                foreach($files as $file){
                    $name    = 'img_'.uniqid().'.png';
                    $dataImg = explode(',', $file);
                    $decoded = base64_decode($dataImg[1]);
                    file_put_contents(storage_path(). '/app/public/uploads/photos/'.$name,$decoded);
                    $images[]=$name;
                }
            }

            if($files=$request->input('old_image')){
                foreach($files as $file){
                    $images[]=$file;
                }
            }

        $data->photo = implode('|', $images);

        $data->save();

        return redirect()->route('photos.index')->with('success', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Photo::find($id);

        $deleteImage = Photo::where('id', $id)->first();

        $filePath = storage_path('app/public/uploads/photos');
        $fileToDelete = $filePath . '/' . $deleteImage->photo;

        File::delete($fileToDelete);

        $data->delete();

        return redirect()->route('photos.index')->with('delete-success', 'Deleted');
    }

    public function restore($id)
    {
        Photo::withTrashed()->find($id)->restore();
        
    }
}

resources/views/dashboard/photos/create.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')

<div id="layoutSidenav">
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <ol class="breadcrumb mb-4 mt-4">
                    <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('photos.index') }}">Photo List</a></li>
                    <li class="breadcrumb-item active">Create</li>
                </ol>

                <form action="{{ route('photos.store') }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="row">
                        <div class="col-lg-6 col-12">
                            <h4 class="page-title mt-2 text-white">
                                Add Photo
                            </h4>
                        </div>
                        <div class="col-12 col-md-2 col-lg-2 offset-md-4 offset-lg-4">
                            <button type="submit" class="btn btn-info form-group btn-block">
                                Save
                            </button>
                        </div>
                        <div class="col-12 mb-4">
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="title">Title</label>
                                        <input type="text" class="form-control" id="title" name="title"
                                            placeholder="Enter Title">
                                        @error('title') <p class="fields-error" style="color: red;">{{ $message }}
                                        </p>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="description">Description</label>
                                        <textarea class="form-control" id="description" name="description"
                                            rows="3"></textarea>
                                        @error('description') <p class="fields-error" style="color: red;">
                                            {{ $message }}
                                        </p>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="category">Category</label>
                                        <select class="form-control" id="category_id" name="category">
                                            <option disabled selected>Select Category</option>
                                            @forelse($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->category_name }}
                                            </option>
                                            @empty
                                            <option>No Category</option>
                                            @endforelse
                                        </select>
                                        @error('category') <p class="fields-error" style="color: red;">
                                            {{ $message }}
                                        </p>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="card">
                                                    <div class="card-body drop-images text-center">
                                                        <p><i class="fas fa-cloud-download-alt"></i></p>
                                                        <p class="text-black">Drag and Drop Images here or <br>Click
                                                            to
                                                            Upload</p>
                                                        <input type="file" class="drag-files" id="uploadFiles"
                                                            multiple="multiple" name="images_file[]"
                                                            accept=".gif, .png, .jpg, .jpeg">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-12 m-t-20 my-upload-pets text-center">
                                                <label for="">Uploaded Images</label>
                                                <input type="hidden" name="album_id"
                                                    value="<?=isset($_GET['album_id'])?$_GET['album_id']:0?>">
                                                <div class="card">
                                                    <div class="card-body uploaded-images">
                                                        <div class="row uploaded-files">
                                                            <div class="col-md-12" id="emptyImg">
                                                                <div class="alert alert-info" role="alert">
                                                                    Images uploaded will be display here.
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </main>
        @include('partials.footer.index')
    </div>
</div>

@endsection

@section('scripts')
<script>
    var rmimg = (e) => {
        $(e).parent().remove();
        var img_uploaded = $('.img_uploaded').length;
        if(img_uploaded == 0){
        $("#emptyImg").html(''+
        '<div class="alert alert-info" role="alert">'+
            'Images uploaded will be display here.'+
            '</div>'
        );
        }
    }

    if(window.File && window.FileList && window.FileReader) {
    $("#uploadFiles").on("change", function(e) {
        var files = e.target.files,
        filesLength = files.length;
        for (var i = 0; i < filesLength; i++) {
            var f = files[i];
            var fileReader = new FileReader();
            if(f.size < 3000000){
                fileReader.onload = (function(e) {
                    $("#emptyImg").html('');
                    $(".uploaded-files").append('<div class="col-md-3 img_uploaded">'+
                        '<div class="website-img">'+
                            '<img class="w-100" src="'+e.target.result+'" alt="Pet Image">'+
                        '</div>'+
                        '<span class="cust-mod-close rmImg" title="Remove Image" onclick="rmimg(this)"><i class="fa fa-times text-white"></i></span>'+
                        '<input name="website_image[]" value="'+ e.target.result +'" hidden>'+
                    '</div>');
                });
                fileReader.readAsDataURL(f);
            } else{
                swal('Failed', "Image should less than 3 MB or 3000kb", 'warning');
            }
        }
    });
} else {
    swal('Failed', "Your browser doesn't support to File API", 'warning');
}

  
</script>
@endsection