routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'AppController@index')->name('index');
Route::get('/about')->uses('HomeController@about')->name('about');
Route::get('/firesafety')->uses('HomeController@firesafety')->name('firesafety');
Route::get('/view-images/{id}')->uses('HomeController@viewImages')->name('view-images');

Auth::routes();

Route::prefix('/')->middleware(['auth', 'two_factor_auth'])->namespace('Dashboard')->group( function(){

    Route::resource('dashboard/photos', 'Photos\PhotosController');
    Route::resource('dashboard/category', 'Category\CategoryController');
    Route::resource('dashboard/profile-settings', 'UserSettings\UserSettingsController');

    //Change password
    Route::get('dashboard/change_password', 'UserSettings\UserSettingsController@change_password_form')->name('change_password');
    Route::post('dashboard/change_password', 'UserSettings\UserSettingsController@change_password')->name('change_password');

    //Restore Category
    Route::get('dashboard/category/restore/{category}', 'Category\CategoryController@restore')->name('restore');
    Route::post('dashboard/category/restore/{category}', 'Category\CategoryController@restore')->name('restore');

    //Restore Photos
    Route::get('dashboard/photos/restore/{photo}', 'Photos\PhotosController@restore');
    Route::post('dashboard/photos/restore/{photo}', 'Photos\PhotosController@restore');

    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
});

Route::get('/2fa', 'TwoFactorController@show2faForm');
Route::post('/2fa', 'TwoFactorController@verifyToken');

app/Models/Dashboard/Category.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Model;
use App\Models\Dashboard\Photo;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function photos()
    {
        return $this->hasMany(Photo::class);
    }
}

app/Models/Dashboard/Photo.php
<?php

namespace App\Models\Dashboard;

use Illuminate\Database\Eloquent\Model;
use App\Models\Dashboard\Category;
use Illuminate\Database\Eloquent\SoftDeletes;

class Photo extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/Dashboard/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Dashboard\Category;
use DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $data = Category::all();
        // Category::where('id', 3)->withTrashed()->get();
        if(request()->ajax())
        {
            return DataTables::of(Category::withTrashed()->latest()->get())
                ->addColumn('action', function($data){
                    if($data->deleted_at == null) {
                    $actionButtons = '<a href="/dashboard/category/'.$data->id.'/edit" class="mr-2 btn btn-warning editBtn">
                                        <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <form action="" style="display: inline">
                                            '.csrf_field().'
                                            <button type="button" class="mr-2 btn btn-danger deleteBtn" onclick="deleteData('.$data->id.')">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                        <button type="button" class="btn btn-primary" disabled style="opacity: .5;">
                                            <i class="fas fa-trash-restore"></i>
                                        </button>';
                    return $actionButtons;
                    } else{
                        $actionButtons = '<a class="mr-2 btn btn-warning editBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <button class="mr-2 btn btn-danger deleteBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                        <form action="/dashboard/category/restore/'.$data->id.'" method="POST" style="display: inline;>
                                        '.csrf_field().'
                                            <button type="button" class="btn btn-primary" onclick="restoreData('.$data->id.')">
                                                <i class="fas fa-trash-restore"></i>
                                            </button>
                                        </form>';

                        return $actionButtons;
                    }
                })
                ->rawColumns(['action'])
                ->make(true);
               
        };

        return view('dashboard.category.index', compact('data'));
    }

    public function getId($id)
    {
        $data = Category::find($id);

        return $data;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'category' => 'required',
        ]);

        $categories = new Category;

        $categories->category_name = $request->input('category');

        $categories->save();

        return redirect()->route('category.index')->with('success', 'Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('dashboard.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($id);

        $category->category_name = $request->input('category');

        $category->save();

        return redirect()->route('category.index')->with('success', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);

        $category->delete();

        return redirect()->route('category.index')->with('delete-success', 'Deleted');
    }

    public function restore($id)
    {
        Category::withTrashed()->find($id)->restore();
        
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;;
use App\Models\Dashboard\Category;
use App\Models\Dashboard\Photo;

class HomeController extends Controller
{
    public function index(){

        $photos = Photo::count();
        $category = Category::count();
        
        return view('dashboard.index', compact(['photos', 'category']));
    }
    
}

app/Http/Controllers/Dashboard/Photos/PhotosController.php
<?php

namespace App\Http\Controllers\Dashboard\Photos;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Dashboard\Photo;
use App\Models\Dashboard\Category;
use DataTables;
use File;

class PhotosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax())
        {
            return DataTables::of(Photo::withTrashed()->latest()->get())
                ->editColumn('photo', function($data){

                $images = explode('|', $data->photo);
                $imgUrl = $data->photo ? 'photos/'.$images[0] : 'default_image.png';
                $photo = '
                    <a href="/storage/uploads/'.$imgUrl.'" class="image-popup" title="'.$data->title.'">
                        <div class="tbl-img">
                            <img src="/storage/uploads/'.$imgUrl.'" alt="'.$data->title.'">
                        </div>
                    </a>
                ';
                    return $photo;
                })

                ->editColumn('category_name', function($data){

                    $category = $data->category->category_name;

                    return $category;
                })

                ->editColumn('title',function($data){
                    return \Str::limit(strip_tags($data->title),10);

                 })

                ->editColumn('description',function($data){
                    return \Str::limit(strip_tags($data->description),30);

                 })

                ->addColumn('action', function($data){
                    if($data->deleted_at == null) {
                    $actionButtons = '<a href="/dashboard/photos/'.$data->id.'/edit" class="mr-2 btn btn-warning editBtn">
                                        <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <form action="" style="display: inline;">
                                            '.csrf_field().'
                                            <button type="button" class="btn btn-danger deleteBtn" onclick="deleteData('.$data->id.')">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                        <button type="button" class="btn btn-primary" disabled style="opacity: .5;">
                                            <i class="fas fa-trash-restore"></i>
                                        </button>';
                    return $actionButtons;
                    } else{
                        $actionButtons = '<a class="mr-2 btn btn-warning editBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <button class="mr-2 btn btn-danger deleteBtn" style="pointer-events: none; cursor: default; opacity: .5;">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                        <form action="/dashboard/photos/restore/'.$data->id.'" method="POST" style="display: inline;>
                                        '.csrf_field().'
                                            <button type="button" class="btn btn-primary" onclick="restoreData('.$data->id.')">
                                                <i class="fas fa-trash-restore"></i>
                                            </button>
                                        </form>';
                    return $actionButtons;
                    }
                })
                ->rawColumns(['action', 'photo', 'category_name', 'title', 'description'])
                ->make(true);
        };

        return view('dashboard.photos.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('dashboard.photos.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'description' => 'required',
            'category' => 'required',
            // 'photo' => 'required|image|nullable|mimes:jpeg,png,jpg,gif,svg',

        ]);

        $input=$request->all();
            $images=array();
            $files = $request->input('website_image');
            if($files){
                foreach($files as $file) {
                    $filename = 'img_'.uniqid().'.png';
                    $dataImg  = explode(',', $file);
                    $decoded  = base64_decode($dataImg[1]);
                    file_put_contents(storage_path(). '/app/public/uploads/photos/'.$filename,$decoded);
                    $images[]=$filename;
                }
            }

        $data = new Photo;
        $data->title = $request->input('title');
        $data->description = $request->input('description');
        $data->category_id = $request->input('category');
        $data->photo = implode("|",$images);

        $data->save();

        return redirect()->route('photos.index')->with('success', 'Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::all();
        $data = Photo::find($id);
        return view('dashboard.photos.edit', compact('data', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $data = Photo::find($id);
        $data->title = $request->input('title');
        $data->description = $request->input('description');
        $data->category_id = $request->category_id;

        $input=$request->all();
            $images=array();
            $files = $request->input('website_image');
            if($files){
                foreach($files as $file){
                    $name    = 'img_'.uniqid().'.png';
                    $dataImg = explode(',', $file);
                    $decoded = base64_decode($dataImg[1]);
                    file_put_contents(storage_path(). '/app/public/uploads/photos/'.$name,$decoded);
                    $images[]=$name;
                }
            }

            if($files=$request->input('old_image')){
                foreach($files as $file){
                    $images[]=$file;
                }
            }

        $data->photo = implode('|', $images);

        $data->save();

        return redirect()->route('photos.index')->with('success', 'Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Photo::find($id);

        $deleteImage = Photo::where('id', $id)->first();

        $filePath = storage_path('app/public/uploads/photos');
        $fileToDelete = $filePath . '/' . $deleteImage->photo;

        File::delete($fileToDelete);

        $data->delete();

        return redirect()->route('photos.index')->with('delete-success', 'Deleted');
    }

    public function restore($id)
    {
        Photo::withTrashed()->find($id)->restore();
        
    }
}

resources/views/dashboard/profile_settings/change_password.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')

<div id="layoutSidenav">
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <ol class="breadcrumb mb-4 mt-4">
                    <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                    <li class="breadcrumb-item active">Profile Settings</li>
                </ol>
                <hr>
                <div class="col-12 px-3">
                    @include('partials.messages.messages')
                </div>

                <form action="{{ route('change_password') }}" method="POST" class="form-horizontal" role="form">
                    {{ csrf_field() }}

                    <div class="card">
                        <div class="card-header">
                            <h5>Change Password</h5>
                        </div>
                        <div class="card-body">
                            <div class="row" style="margin-top: 20px;">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Current Password</label>
                                        <input class="form-control" type="password" name="current_password"
                                            placeholder="Current Password">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label>New Password</label>
                                    <input class="form-control" type="password" name="password"
                                        placeholder="New Password">
                                </div>
                                <div class="col-md-4">
                                    <label>Confirm Password</label>
                                    <input class="form-control" type="password" name="password_confirmation"
                                        placeholder="Confirm Password">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-2 col-lg-2 offset-md-4 offset-lg-4 ml-auto">
                                    <button type="submit" class="btn btn-info form-group btn-block">
                                        Change Password
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <hr>
        </main>
        @include('partials.footer.index')
    </div>
</div>

@endsection

@section('scripts')

@endsection

resources/views/dashboard/profile_settings/index.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')

<div id="layoutSidenav">
    <div id="layoutSidenav_content">
        <main>
            <div class="container-fluid">
                <ol class="breadcrumb mb-4 mt-4">
                    <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
                    <li class="breadcrumb-item active">Profile Settings</li>
                </ol>
                <hr>
                <div class="col-12 px-3">
                    @include('partials.messages.messages')
                </div>
                @foreach($user as $data)
                <form action="{{ route('profile-settings.update', ['profile_setting' => $data->id]) }}" method="POST"
                    class="form-horizontal" role="form" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    @method('PUT')
                    <div class="card">
                        <div class="card-header">
                            <h5>Profile Info</h5>
                        </div>
                        <div class="card-body">
                            <div class="row" style="margin-top: 20px;">
                                <div class="col-md-12">
                                    <div class="image-upload">
                                        @if($data->profile_pic == '')
                                        <input type="file" name="profile_pic" class="dropify form-control"
                                            data-default-file="{{ '/storage/profile_pic/default_profile_pic.png' }}">
                                        @else
                                        <input type="file" name="profile_pic" class="dropify form-control"
                                            data-default-file="{{ '/storage/profile_pic/'.$data->profile_pic.'' }}">
                                        @endif
                                        <p class="text-center mt-10 b-700">Upload Profile Pic</p>
                                    </div>
                                </div>
                            </div>
                            <div class="row" style="margin-top: 20px;">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input class="form-control" type="text" name="name" placeholder="Name"
                                            value="{{ $data->name }}">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <label>Email</label>
                                    <input class="form-control" type="text" name="email" placeholder="Email"
                                        value="{{ $data->email }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <div class="custom-control custom-switch">
                                            <input type="checkbox" class="custom-control-input" id="two-factor-auth" name="twoFactorAuth" {{  ($data->two_factor_option == 1 ? ' checked' : '') }}>
                                            <label class="custom-control-label" for="two-factor-auth">Enable Two Factor Authentication</label>
                                          </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-2 col-lg-2 offset-md-4 offset-lg-4 ml-auto">
                                    <button type="submit" class="btn btn-info form-group btn-block">
                                        Update Profile
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {{-- <div class="row">
                        <div class="col-md-3">
                            <div class="text-center">
                                <input type="file" name="profile_pic" class="dropify form-control">
                            </div>
                        </div>
                    </div> --}}
                </form>
                @endforeach
            </div>
            <hr>
        </main>
        @include('partials.footer.index')
    </div>
</div>

@endsection

@section('scripts')
<script>
    $('.dropify').dropify();
    function myFunction() {
        var x = document.getElementById("password-field");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }

</script>
@endsection